export type CaseStudy = {
  id: number;
  title: string;
  category: string;
  description: string;
  imageUrl: string;
  fullContent: string;
};

export const caseStudies: CaseStudy[] = [
  {
    id: 1,
    title: "Attack pattern detection",
    category: "FRAUD PREVENTION",
    description: "BOT traffic hitting web with various patterns can be detected and averted. Traffic can be diverted to Honey Pot content generated by AI to gather information.",
    imageUrl: "https://www.researchdive.com/blogImages/OtGmhpxDz1.jpeg",
    fullContent: `Our advanced attack pattern detection system provides robust protection against sophisticated BOT attacks targeting web applications. 

    Key Features:
    • Real-time pattern recognition and analysis
    • AI-powered behavioral analysis
    • Intelligent honeypot deployment
    • Comprehensive threat intelligence gathering
    • Automated response mechanisms

    The system employs machine learning algorithms to identify and categorize various attack patterns, enabling swift response to emerging threats. When suspicious activity is detected, the traffic is seamlessly redirected to AI-generated honeypot content, allowing us to gather valuable intelligence about attack methodologies while keeping genuine users safe.

    Implementation Results:
    • 95% reduction in successful bot attacks
    • 60% improvement in threat intelligence gathering
    • 80% faster response to new attack patterns
    • Minimal impact on legitimate user experience`
  },
  {
    id: 2,
    title: "Device location (Telecom)",
    category: "FRAUD PREVENTION",
    description: "Detect exact location of customer device irrespective of IP by tapping into wireless provider network. Allowing to avoid physical store fraud with fraudster.",
    imageUrl: "https://intersec.com/hs-fs/hubfs/telecom.jpg?width=900&height=525&name=telecom.jpg",
    fullContent: `Our telecom-integrated device location system provides unprecedented accuracy in determining user device locations, significantly enhancing fraud prevention capabilities in physical retail environments.

    Key Features:
    • Direct telecom network integration
    • Real-time location verification
    • IP-independent tracking
    • Multi-factor location authentication
    • Automated risk assessment

    The solution leverages direct partnerships with wireless providers to obtain precise device locations, circumventing traditional IP-based geolocation limitations. This enables businesses to verify customer presence in physical stores and detect potential fraudulent activities.

    Implementation Results:
    • 85% reduction in physical store fraud attempts
    • 99.9% location accuracy
    • 70% faster fraud detection
    • Seamless customer experience for legitimate transactions`
  },
  {
    id: 3,
    title: "Dynamic attribute extraction",
    category: "FRAUD PREVENTION",
    description: "Capability to tap inbound data and extract meaningful information out of it, reducing integration footprint.",
    imageUrl: "https://www.xpand-it.com/wp-content/uploads/2022/08/Fraude_blog-1.png",
    fullContent: `Our dynamic attribute extraction system revolutionizes how businesses process and analyze inbound data streams for fraud prevention.

    Key Features:
    • Real-time data processing
    • Intelligent pattern recognition
    • Automated attribute classification
    • Minimal integration requirements
    • Scalable architecture

    The system automatically identifies and extracts relevant attributes from various data sources, significantly reducing the need for complex integrations while maintaining comprehensive fraud detection capabilities.

    Implementation Results:
    • 75% reduction in integration complexity
    • 90% faster data processing
    • 65% improvement in fraud detection accuracy
    • 50% reduction in false positives`
  }
];